### ISSUE TITLE
TDT crashes on opening second instance

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#379]
**Expected Behaviour:** A second instance of TDT should open when the icon is selected.
**Actual Behaviour:** The app freezes and then crashes with the error message 

> An unexpected error ocurred Object reference not set to an instance of an object. Please see Help -> Show Error Log for more details
**Error Log:** ```
[2019-02-11 16:47:34] An unexpected error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Client.MainWindow.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by caseydiers** [comment]
This appears to have been previously fixed as I use multiple instances regularly and have never run into this issue.
