### ISSUE TITLE
Minimise to system tray - error "Hotkey already in use"

### ISSUE THREAD

**Issue by podtor** [benrhughes/todotxt.net#396]
I pinned to taskbar Todotxt.net and check the option "Minimise to system tray", after minimise and click on pin shortcut show error "Hotkey already in use"

**log**
[11/10/2019 9:15:28 AM] Error Global HotKey Registered
System.ApplicationException: Hotkey already in use
   at Client.HotKey.RegisterHotKey()
   at Client.HotKey..ctor(ModifierKeys modifierKeys, Keys key, IntPtr windowHandle)
   at Client.HotKeyMainWindows..ctor(Window window, ModifierKeys modifierKeys, Keys key)

**Comment by chucku** [comment]
I have the same problem.

**Comment by caseydiers** [comment]
This error just started occuring for me as well.  I'm not sure what changed.  That setting was checked for me as well, althought I don't recall changing that setting recently.  I guess for now I'll just uncheck that setting, which does make the error stop occuring.
